name: Delete Old Workflow Runs

on:
  workflow_dispatch: # 手動実行ボタンを有効化

permissions:
  actions: write

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1          # 直近3日間に実行された履歴は残す
          keep_minimum_runs: 5    # 最新の5件の履歴は必ず残す
          delete_workflow_by_status_current: "completed,cancelled" # 失敗は残す
          # 👇 ここに消したいワークフローの名前（Actionsタブの左メニューの表記）を正確に書いてください
          workflow_name_input: "Update Arbitrage Data"
